# Generated by Django 4.2.17 on 2024-12-20 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('altpoet', '0001_initial'), ('altpoet', '0002_document_remove_img_page_alt_img_delete_page_and_more'), ('altpoet', '0003_alter_document_item_alter_img_document_and_more'), ('altpoet', '0004_img_is_figure'), ('altpoet', '0005_alter_img_img_id'), ('altpoet', '0006_alter_image_url'), ('altpoet', '0007_alter_alt_text')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=80)),
                ('hash', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('url', models.CharField(max_length=80, unique=True)),
                ('basepath', models.CharField(default='/{item)', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='', max_length=80)),
                ('base', models.CharField(default='', max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='altpoet.project')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.CharField(max_length=80, unique=True)),
                ('img_type', models.IntegerField(default=0)),
                ('described_by', models.CharField(max_length=80, null=True)),
                ('alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imgs', to='altpoet.image')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='altpoet.image')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='altpoet.document')),
            ],
        ),
        migrations.CreateModel(
            name='Alt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alts', to='altpoet.agent')),
                ('img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alts', to='altpoet.img')),
            ],
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('project', 'item'), name='doc_unique_in_project'),
        ),
        migrations.AddConstraint(
            model_name='img',
            constraint=models.UniqueConstraint(fields=('document', 'img_id'), name='img_unique_in_doc'),
        ),
        migrations.AddField(
            model_name='img',
            name='is_figure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='img',
            name='img_id',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='alt',
            name='text',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
