# Generated by Django 4.2.20 on 2025-03-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0001_squashed_0007_alter_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='alt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imgs', to='altpoet.alt'),
        ),
    ]
