# Generated by Django 4.2.20 on 2025-04-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0008_alter_img_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filesize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='hash',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['hash'], name='altpoet_ima_hash_f0856c_idx'),
        ),
    ]
