# Generated by Django 4.2.20 on 2025-04-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0009_image_filesize_image_x_image_y_alter_image_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
