# Generated by Django 4.2.20 on 2025-04-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0009_usersubmission_usersubmission_unique_submission'),
        ('altpoet', '0010_alter_image_hash'),
    ]

    operations = [
    ]
