# Generated by Django 4.2.20 on 2025-04-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0008_alter_img_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_json', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_document', to='altpoet.document')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_submitted', to='altpoet.agent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usersubmission',
            constraint=models.UniqueConstraint(fields=('document', 'source'), name='unique_submission'),
        ),
    ]
