# Generated by Django 4.2.20 on 2025-04-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0010_alter_image_hash'),
        ('altpoet', '0011_usersubmission_usersubmission_unique_submission'),
    ]

    operations = [
    ]
