# Generated by Django 4.2.20 on 2025-04-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0011_merge_20250428_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='submission_type',
            field=models.CharField(choices=[('SV', 'Save'), ('SB', 'Submit')], default='SV', max_length=2),
        ),
    ]
