# Generated by Django 4.2.20 on 2025-05-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0014_alt_user_sub'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alt',
            constraint=models.UniqueConstraint(fields=('img', 'source'), name='alt_unique_per_user'),
        ),
    ]
