# Generated by Django 4.2.20 on 2025-06-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0015_alt_alt_unique_per_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='submission_type',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='user_json',
        ),
    ]
