# Generated by Django 4.2.23 on 2025-06-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0016_remove_usersubmission_submission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
