# Generated by Django 4.2.23 on 2025-07-16 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0017_document_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserAltVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('UP', 'Upvote'), ('DN', 'Downvote'), ('NO', 'No vote')], default='NO', max_length=2)),
                ('alt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_voted', to='altpoet.alt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='altpoet.agent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='useraltvote',
            constraint=models.UniqueConstraint(fields=('user', 'alt'), name='alt_vote_unique_per_user'),
        ),
    ]
