# Generated by Django 4.2.23 on 2025-09-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0018_alt_votes_useraltvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='user_status',
            field=models.IntegerField(choices=[(0, 'No Progress'), (1, 'In Progress'), (2, 'Complete')], default=1),
        ),
    ]
