# Generated by Django 4.2.23 on 2025-09-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0019_usersubmission_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubmission',
            old_name='user_status',
            new_name='status',
        ),
    ]
