# Generated by Django 4.2.23 on 2025-12-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0020_rename_user_status_usersubmission_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('change_submission_status_tier_one', 'Can change the status of this document if submitted by tier 0 (volunteer, non-staff)'), ('change_submission_status_tier_two', 'Can always change the status of this document')]},
        ),
        migrations.AlterModelOptions(
            name='img',
            options={'permissions': [('set_preferred_alt', 'Can set the preferred alt text for this image')]},
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(0, 'No Progress'), (1, 'In Progress'), (2, 'Complete')], default=1),
        ),
    ]
