# Generated by Django 4.2.23 on 2025-12-10 00:56

from django.db import migrations, models
from django.contrib.auth.models import Group, Permission

class Migration(migrations.Migration):

    def add_group_permissions(apps, schema_editor):
        group1, created1 = Group.objects.get_or_create(name='Tier1')
        if created1:
            permissions = Permission.objects.filter(
                codename__in=[
                    'change_submission_status_tier_one',
                    'set_preferred_alt',
                ]
            )
            for p in permissions:
                group1.permissions.add(p)
                group1.save()
        group2, created2 = Group.objects.get_or_create(name='Tier2')
        if created2:
            permissions = Permission.objects.filter(
                codename__in=[
                    'change_submission_status_tier_two',
                    'set_preferred_alt',
                ]
            )
            for p in permissions:
                group2.permissions.add(p)
                group2.save()

    dependencies = [
        ('altpoet', '0021_alter_document_options_alter_img_options_and_more'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
