# Generated by Django 4.2.23 on 2025-12-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altpoet', '0022_auto_20251210_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='review_urgency',
            field=models.IntegerField(default=0),
        ),
    ]
